# Generated by Django 3.2.6 on 2022-12-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='book2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='reservation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='予約日'),
        ),
    ]
