# Generated by Django 3.2.6 on 2022-12-23 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobplace', '0002_auto_20221224_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='book3',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
