# Generated by Django 3.2.6 on 2023-01-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobplace', '0004_remove_historymodel_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='reservation_day',
            field=models.DateTimeField(verbose_name='予約日'),
        ),
    ]
