# Generated by Django 3.2.6 on 2023-01-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobplace', '0005_alter_historymodel_reservation_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historymodel',
            name='reservation_day',
        ),
    ]
